# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of resources to be Applied
resources:
#- bookinfo-tls-secret-cert.yaml
- grafana.yaml
- istio-base.yaml
- istio-eastwestgateway.yaml
- istio-ingressgateway.yaml
- istiod.yaml
- kiali.yaml
- prometheus.yaml
- tls-secret-cert.yaml